############################
## CHANGE THESE
############################

baseURL: "https://friendsofbramleypark.com"
title: Friends of Bramley Park

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-gb"
enableRobotsTXT: true
