############################
## CHANGE THESE
############################

baseURL: "https://Friends-of-Bramley-Park.github.io/friendsofbramleypark.com"
title: friendsofbramleypark.com

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
